title: Linux and Electronics
description: My journey of making electronics projects with Linux.
show_downloads: false
google_analytics: true
theme: jekyll-theme-hacker
comments: true
google_analytics: UA-113147957-1
